import sys
import os
import country
from collections import deque
from typing import Dict, Any
from enum import Enum

# python refactor

balance: deque()

# Dict of nations to players. [Tag, playerName]
players: dict[str, str] = {}

# Dict of nations to their country information. <Tags, Country>
# @todo: need to convert country.py to a class and use that as the secondary object here.
# countries: Dict[str, Country] = {}
countries: dict[str, country] = {}

# Checks to see if there is an bracket or paranthesis, the adds/removes from the stack as necessary.
def updateBalance(file_string: str) -> None:
  i = 0
  while i != file_string.length():
    # Find a front brace and put it on the stack
    if file_string[i] == '{' or file_string[i] == '(':
      balance.push(file_string[i])
    
    # Match end brace with proper front brace
    # If properly matched remove the front brace from the stack
    elif file_string[i] == '}' or file_string[i] == ')':
      if balance.top() == '{' and file_string[i] == '}' or balance.top() == '(' and file_string[i] == ')':
        balance.pop()
      else:
        break

    i += 1

# @todo: moveForwardALineInFile needs to be modified to actually be a line in the file <- wrong, actually just pass in a string, do your thing, then return. The main method will handle moving between strings.
# This reads through the 'player_countries' section of a save file.
# assumes that each line contains a single item, in the order of "player_name" -> "tag"
def updatePlayerArray():
  check_for_player = 0
  player_name: str
  tag_regex = "[A-Za-z]{1}[A-Za-z0-9]{2}\"$"
  while (balance.count != 0 and moveForwardALineInFile):
    if check_for_player % 2 == 0:
      # @todo: updateBalance() needs arguments.
      updateBalance()
      player_name = moveForwardALineInFile
    else:
      tag = re.search(tag_regex, moveForwardALineInFile)
      if tag:
        players.update([tag, player_names])

# Get'em started
def main(argv):
  saveFileName = sys.argv[1]

  if not os.path.isfile(saveFileName):
    print("File not found at {}".format(saveFileName))
    sys.exit()
  
  with open(saveFileName) as saveFile:
    for currentLine, line in enumerate(saveFile):
      print("Line {}; {}".format(currentLine, line))

# List of all artillery unit types
class Artillery(Enum):
  HOUFNICE = 1
  LARGE_CAST_IRON_BOMBARD = 2
  CULVERIN = 3
  PEDRERO = 4
  LARGE_CAST_IRON_CANNON = 5
  SMALL_CAST_IRON_CANNON = 6
  CHAMBERED_DEMI_CANNON = 7
  LEATHER_CANNON = 8
  SWIVEL_CANNON = 9
  COEHORN_MORTAR = 10
  ROYAL_MORTAR = 11
  FLYING_BATTERY = 12

# List of all calvary unit types
class Calvary(Enum):
  AFRICAN_ABYSSINIAN_CAVALRY = 0
  AFRICAN_ABYSSINIAN_LIGHT_CAVALRY = 1
  AFRICAN_CUIRASSIER = 2
  AFRICAN_DRAGOON = 3
  AFRICAN_HUSSAR = 4
  AFRICAN_MANDELAKU = 5
  AFRICAN_MOSSI_HORSEMEN = 6
  AFRICAN_SOMALI_CAVALRY = 7
  AFRICAN_SWARM = 8
  AFRICAN_TUAREG_CAVALRY = 9
  AFSHARID_REFORMED = 10
  ALI_BEY_REFORMED_INFRANTRY = 11
  ASIAN_CHARGE_CAVALRY = 12
  AUSTRIAN_HUSSAR = 13
  BHONSLE_CAVALRY = 14
  BRITISH_HUSSAR = 15
  CENTRAL_AMERICAN_DRAGOON = 16
  CENTRAL_AMERICAN_HORSEMEN = 17
  CENTRAL_AMERICAN_HUSSAR = 18
  CENTRAL_AMERICAN_RIFLE_CAVALRY = 19
  CENTRAL_AMERICAN_SWARM = 20
  CHEVAUCHEE = 21
  CHINESE_DRAGOON = 22
  CHINESE_STEPPE = 23
  COMMANCHE_SWARM = 24
  DRUZHINA_CAVALRY = 25
  DURRANI_DRAGOON = 26
  DURRANI_SWIVEL = 27
  EAST_MONGOLIAN_STEPPE = 28
  EASTERN_BOW = 29
  EASTERN_KNIGHTS = 30
  EASTERN_SKIMISHER = 31
  EASTERN_UHLAN = 32
  FRENCH_CARABINIER = 33
  FRENCH_CARACOLLE = 34
  FRENCH_CUIRASSIER = 35
  FRENCH_DRAGOON = 36
  HUNGARIAN_HUSSAR = 37
  INDIAN_ARCHERS = 38
  INDIAN_ELEPHANT = 39
  INDIAN_SHOCK_CAVALRY = 40
  JAPANESE_SAMURAI = 41
  MAHARATHAN_CAVALRY = 42
  MAMLUK_CAVALRY_CHARGE = 43
  MAMLUK_MUSKET_CHARGE = 44
  MANCHU_BANNER = 45
  MONGOL_BOW = 46
  MONGOL_MANSABDAR = 47
  MONGOL_STEPPE = 48
  MONGOL_SWARM = 49
  MUGHAL_MUSKETEER = 50
  MUSCOVITE_CARACOLLE = 51
  MUSCOVITE_COSSACK = 52
  MUSLIM_CAVALRY_ARCHERS = 53
  MUSLIM_DRAGOON = 54
  NAPOLEONIC_LANCERS = 55
  NATIVE_INDIAN_HORSEMEN = 56
  NORTH_AMERICAN_DRAGOON = 57
  NORTH_AMERICAN_HORSEMEN = 58
  NORTH_AMERICAN_HUSSAR = 59
  NORTH_AMERICAN_RIFLE_CAVALRY = 60
  NORTH_AMERICAN_SWARM = 61
  OPEN_ORDER_CAVALRY = 62
  OTTOMAN_LANCER = 63
  OTTOMAN_MUSELLEM = 64
  OTTOMAN_REFORMED_SPAHI = 65
  OTTOMAN_SPAHI = 66
  OTTOMAN_TIMARIOT = 67
  OTTOMAN_TOPRAKLI_DRAGOON = 68
  OTTOMAN_TOPRAKLI_HIT_AND_RUN = 69
  PERSIAN_CAVALRY_CHARGE = 70
  POLISH_HUSSAR = 71
  POLISH_WINGED_HUSSAR = 72
  PRUSSIAN_UHLAN = 73
  QIZILBASH_CAVALRY = 74
  RAJPUT_HILL_FIGHTERS = 75
  REFORMED_ASIAN_CAVALRY = 76
  REFORMED_MANCHU_RIFLE = 77
  REFORMED_MUGHAL_MANSABDAR = 78
  RUSSIAN_COSSACK = 79
  RUSSIAN_CUIRASSIER = 80
  RUSSIAN_LANCER = 81
  SHAYBANI = 82
  SHWARZE_REITER = 83
  SIKH_RIFLE = 84
  SIOUX_DRAGOON = 85
  SLAVIC_STRADIOTI = 86
  SOUTH_AMERICAN_DRAGOON = 87
  SOUTH_AMERICAN_HORSEMEN = 88
  SOUTH_AMERICAN_HUSSAR = 89
  SOUTH_AMERICAN_RIFLE_CAVALRY = 90
  SOUTH_AMERICAN_SWARM = 91
  STEPPE_CAVALRY = 92
  STEPPE_LANCERS = 93
  STEPPE_MOUNTED_RAIDERS = 94
  STEPPE_RIDERS = 95
  STEPPE_UHLANS = 96
  SWEDISH_ARME_BLANCHE = 97
  SWEDISH_GALLOP = 98
  TARTAR_COSSACK = 99
  TOPCHIS_ARTILLERY = 100
  WESTERN_MEDIEVAL_KNIGHTS = 101
  ZAPOROGHIAN_COASSACK = 102

# List of all infantry unit types
class Infantry(Enum):
  ADAL_GUERILLA_WARFARE = 0
  ADAL_GUNPOWDER_WARFARE = 1
  AFRICAN_CLUBMEN = 2
  AFRICAN_HILL_WARFARE = 3
  AFRICAN_SPEARMEN = 4
  AFRICAN_WESTERN_FRANCHISE_WARFARE = 5
  AFSHARID_REFORMED_INFRANTRY = 6
  ALGONKIN_TOMAHAWK_CHARGE = 7
  AMERICAN_WESTERN_FRANCHISE_WARFARE = 8
  ANGLOFRENCH_LINE = 9
  APACHE_GUERILLA = 10
  ASIAN_ARQUEBUSIER = 11
  ASIAN_MASS_INFRANTRY = 12
  ASIAN_MUSKETEER = 13
  AUSTRIAN_GRENZER = 14
  AUSTRIAN_JAEGER = 15
  AUSTRIAN_TERCIO = 16
  AUSTRIAN_WHITE_COAT = 17
  AZTEC_GUNPOWDWER_WARFARE = 18
  AZTEC_HILL_WARFARE = 19
  AZTEX_TRIBAL_WARFARE = 20
  BANTU_GUNPOWDER_WARFARE = 21
  BANTU_PLAINS_WARFARE = 22
  BANTU_TRIBAL_WARFARE = 23
  BARDICHE_INFANTRY = 24
  BHONSLE_INFRANTRY = 25
  BRITISH_REDCOAT = 26
  BRITISH_SQUARE = 27
  CHINESE_FOOTSOLDIER = 28
  CHINESE_LONGSPEAR = 29
  CREEK_ARQUEBUSIER = 30
  DURRANI_RIFLED_MUSKETEER = 31
  DUTCH_MARUICIAN = 32
  EAST_ASIAN_SPEARMEN = 33
  EASTERN_CARABINIER = 34
  EASTERN_MEDIEVAL_INFANTRY = 35
  EASTERN_MILITIA = 36
  ETHIOPIAN_GUERILLA_WARFARE = 37
  ETHIOPIAN_GUNPOWDER_WARFARE = 38
  ETHIOPIAN_MOUNTAIN_WARFARE = 39
  FRENCH_BLUECOAT = 40
  FRENCH_IMPULSE = 41
  GAELIC_FREE_SHOOTER = 42
  GAELIC_GALLOGLAIGH = 43
  GAELIC_MERCENARY = 44
  GERMANIZED_PIKE = 45
  HALBERD_INFANTRY = 46
  HAN_BANNER = 47
  HURON_ARQUEBUSIER = 48
  INCA_MOUNTAIN_WARFARE = 49
  INCAN_AXEMEN = 50
  INCAN_GUERILLA_WARFARE = 51
  INCAN_SLINGSHOTS = 52
  INDIAN_ARQUEBUSIER = 53
  INDIAN_FOOTSOLDIER = 54
  INDIAN_RIFLE = 55
  IRISH_CHARGE = 56
  IROQUIS_RIFLE_SCOUT = 57
  IROQUOIS_RIFLE_SCOUT = 58
  ITALIAN_CONDOTTA = 59
  JAPANESE_ARCHER = 60
  JAPANESE_FOOTSOLDIER = 61
  MAHARATHAN_GUERILLA_WARFARE = 62
  MALI_TRIBAL_WARFARE = 63
  MAMLUK_ARCHER = 64
  MAMLUK_DUEL = 65
  MAYA_FOREST_WARFARE = 66
  MAYA_GUERILLA_WARFARE = 67
  MAYA_GUNPWODER_WARFARE = 68
  MAYA_TRIBAL_WARFARE = 69
  MESOAMERICAN_SPEARMEN = 70
  MEXICAN_GUERILLA_WARFARE = 71
  MIXED_ORDER_INFANTRY = 72
  MONGOL_BOW = 73
  MUSCOVITE_MUSKETEER = 74
  MUSCOVITE_SOLDATY = 75
  MUSLIM_MASS_INFANTRY = 76
  NAPOLEONIC_SQUARE = 77
  NATIVE_CLUBMEN = 78
  NATIVE_INDIAN_ARCHERS = 79
  NATIVE_INDIAN_MOUNTAIN_WARFARE = 80
  NATIVE_INDIAN_TRIBAL_WARFARE = 81
  NIGER_KONGOLESE_FOREST_WARFARE = 82
  NIGER_KONGOLESE_GUERILLA_WARFARE = 83
  NIGER_KONGOLESE_GUNPOWDER_WARFARE = 84
  NIGER_KONGOLESE_TRIBAL_WARFARE = 85
  OTTOMAN_AZAB = 86
  OTTOMAN_JANISSARY = 87
  OTTOMAN_NEW_MODEL = 88
  OTTOMAN_NIZAMI_CEDID = 89
  OTTOMAN_REFORMED_JANISSARY = 90
  OTTOMAN_SEKBAN = 91
  OTTOMAN_YAYA = 92
  PERSIAN_FOOTSOLDIER = 93
  PERSIAN_RIFLE = 94
  PERSIAN_SHAMSHIR = 95
  PERUVIAN_GUERILLA_WARFARE = 96
  POLISH_MUSKETEER = 97
  POLISH_TERCIO = 98
  PRUSSIAN_DRILL = 99
  PRUSSIAN_FREDERICKIAN = 100
  PUEBLO_AMBUSH = 101
  RAJPUT_MUSKETEERS = 102
  REFORMED_ASIAN_MUSKETEER = 103
  REFORMED_MUGHAL_MUSKETEER = 104
  REFORMED_STEPPE_RIFLES = 105
  REFORMED_WESTERNIZED_INCAN = 106
  RUSSIAN_GREEN_COAT = 107
  RUSSIAN_MASS = 108
  RUSSIAN_PRETRINE = 109
  SAXON_INFANTRY = 110
  SCOTTISH_HIGHLANDER = 111
  SIKH_HIT_AND_RUN = 112
  SONGHAI_TRIBAL_WARFARE = 113
  SOUTH_AMERICAN_ARQEBUSIER = 114
  SOUTH_AMERICAN_FOREST_WARFARE = 115
  SOUTH_AMERICAN_GUNPOWDER_WARFARE = 116
  SOUTH_AMERICAN_REFORMED_GUNPOWDER_WARFARE = 117
  SOUTH_AMERICAN_SPEARMEN = 118
  SOUTH_AMERICAN_WARFARE = 119
  SOUTH_INDIAN_MUSKETEER = 120
  SPANISH_TERCIO = 121
  STEPPE_FOOTMEN = 122
  STEPPE_INFANTRY = 123
  STEPPE_MUSKETEERS = 124
  STEPPE_RAIDERS = 125
  STEPPE_RIFLES = 126
  SWEDISH_CAROLINE = 127
  SWEDISH_GUSTAVIAN = 128
  SWISS_LANDSKNECHTEN = 129
  TIPU_SULTAN_ROCKET = 130
  TOFONGSHIS_MUSKETEER = 131
  WESTERN_LONGBOW = 132
  WESTERN_MEDIEVAL_INFANTRY = 133
  WESTERN_MEN_AT_ARMS = 134
  WESTERNIZED_ADAL = 135
  WESTERNIZED_AZTEC = 136
  WESTERNIZED_BANTU = 137
  WESTERNIZED_ETHIOPIAN = 138
  WESTERNIZED_INCAN = 139
  WESTERNIZED_MAYAN = 140
  WESTERNIZED_NIGER_KONGOLESE = 141
  WESTERNIZED_SOUTH_AMERICAN = 142
  WESTERNIZED_ZAPOTEC = 143
  ZAPOTEC_GUNPOWDER_WARFARE = 144
  ZAPOTEC_PLAINS_WARFARE = 145
  ZAPOTEC_TRIBAL_WARFARE = 146
  ZULU_CHEST_AND_HORNS = 147

# List of all transport ship types
class Trasport(Enum):
  COG = 1
  EASTINDIAMAN = 2
  FLUTE = 3
  TRABAKUL = 4
  MERCHANTMAN = 5
  WAR_CANOE = 6
  BRIG = 7

# List of all galley ship types
class Galley(Enum):
  ARCHIPELAGO_FRIGATE = 1
  CHEBECK = 2
  GALIOT = 3
  GALLEASS = 4
  GALLEY = 5
  WAR_GALLEY = 6

# List of all light ship ship types
class Light_Ship(Enum):
  BARQUE = 1
  CARAVEL = 2
  EARLY_FRIGATE = 3
  FRIGATE = 4
  GREAT_FRIGATE = 5
  HEAVY_FRIGATE = 6

# List of all heavy ship ship types
class Heavy_Ship(Enum):
  CARRACK = 1
  EARLY_CARRACK = 2
  GALLEON = 3
  THREEDECKER = 4
  TWODECKER = 5
  WARGALLEON = 6
  MERCHANTMAN = 7

#############################
# Starts Program
#############################
main(sys.argv[1:])